apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-volume-manual
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tarsidi/kafka-volume"

