apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-volume
  labels:
    type: local
spec:
  storageClassName: kafka
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tarsidi/kafka-volume"

